E2E tests for helm/kube, this includes:
- Modify kube/e2e to setup a kube/helm env to deploy the cf-operator
  helm charts. Also, make sure the generated resources are deleted
  at the end of the suite.
- Add new Makefile target, test-helm-e2e to run the above mentioned
  e2e tests.
- Add test-kube-e2e script, so that the new test-helm-e2e target can
  run it.
- Modify the helm chart to ensure each test can define a set of:
  - clusterRole
  - clusterRoleBinding
  - serviceAccount
  per namespace.

Whole e2e test uses default ns.

diff --git a/bin/apply-crds b/bin/apply-crds
--- a/bin/apply-crds
+++ b/bin/apply-crds
@@ -1,8 +1,13 @@
 #!/bin/bash
+set -euo pipefail
 
-set -e
+if ! hash helm 2>/dev/null; then
+  echo "[Error] Please install the helm binary"
+  exit 1
+fi
 
-kubectl apply -f deploy/helm/cf-operator/templates/fissile_v1alpha1_boshdeployment_crd.yaml
-kubectl apply -f deploy/helm/cf-operator/templates/fissile_v1alpha1_extendedjob_crd.yaml
-kubectl apply -f deploy/helm/cf-operator/templates/fissile_v1alpha1_extendedsecret_crd.yaml
-kubectl apply -f deploy/helm/cf-operator/templates/fissile_v1alpha1_extendedstatefulset_crd.yaml
+# Apply CRD´s to the cluster
+helm template deploy/helm/cf-operator  -x templates/fissile_v1alpha1_extendedjob_crd.yaml  | kubectl apply -f -
+helm template deploy/helm/cf-operator  -x templates/fissile_v1alpha1_extendedsecret_crd.yaml  | kubectl apply -f -
+helm template deploy/helm/cf-operator  -x templates/fissile_v1alpha1_extendedstatefulset_crd.yaml  | kubectl apply -f -
+helm template deploy/helm/cf-operator  -x templates/fissile_v1alpha1_boshdeployment_crd.yaml  | kubectl apply -f -
