Improve error messages in the quarks repo

diff --git a/bin/check-scripts b/bin/check-scripts
--- a/bin/check-scripts
+++ b/bin/check-scripts
@@ -1,8 +1,8 @@
 #!/bin/bash
 
 if ! [ -x "$(command -v shellcheck)" ]; then
-  echo 'Warning: shellcheck is not installed. Shell scripts will not be linted.' >&2
-  exit
+  echo '[Error] shellcheck is not installed. Shell scripts will not be linted.' >&2
+  exit 1
 fi
 
 for script in $(find ./bin | xargs file -0 | grep -a shell | perl -pe 's/\0.*//'); do
