Using minikube is optional

diff --git a/bin/up b/bin/up
--- a/bin/up
+++ b/bin/up
@@ -1,11 +1,13 @@
 #!/bin/sh
 
-dockerenv=`minikube docker-env`
-if [ $? -ne 0 ]; then
-  echo "Error: Could not retrieve docker settings from minikube."
-  exit 1
+if type -a minikube >/dev/null 2>/dev/null; then
+    dockerenv=`minikube docker-env`
+    if [ $? -ne 0 ]; then
+        echo "Error: Could not retrieve docker settings from minikube."
+        exit 1
+    fi
+    eval ${dockerenv}
 fi
-eval ${dockerenv}
 
 set -e
 
